"use client";
import { FormEvent, useState } from "react";
import { api, ApiError, ReportReason, ReportTargetContext, ReportTargetType } from "@/lib/api";
import styles from "./report-button.module.css";
const reasons:ReportReason[]=["SPAM","HARASSMENT","HATEFUL_CONTENT","VIOLENCE","NUDITY","IMPERSONATION","MISINFORMATION","OTHER"];
const label=(value:string)=>value.toLowerCase().replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
export function ReportButton({accessToken,targetType,targetId,targetContext,onUnauthorized,className}:{accessToken:string;targetType:ReportTargetType;targetId:string;targetContext?:ReportTargetContext;onUnauthorized:()=>void;className?:string}){
 const [open,setOpen]=useState(false),[details,setDetails]=useState(""),[error,setError]=useState(""),[submitted,setSubmitted]=useState(false),[busy,setBusy]=useState(false);const [reason,setReason]=useState<ReportReason>("SPAM");
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await api.createReport(accessToken,targetType,targetId,reason,details,targetContext);setSubmitted(true);setOpen(false);}catch(e){if(e instanceof ApiError&&e.status===401)return onUnauthorized();setError(e instanceof Error?e.message:"Report could not be submitted.");}finally{setBusy(false);}}
 return <>{<button className={className} disabled={submitted} onClick={()=>setOpen(true)} type="button">{submitted?"Reported":"Report"}</button>}{open&&<div className={styles.backdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}} role="presentation"><section aria-labelledby={`report-${targetId}`} aria-modal="true" className={styles.dialog} role="dialog"><header><div><p>Safety report</p><h2 id={`report-${targetId}`}>Tell us what happened</h2></div><button aria-label="Close report dialog" onClick={()=>setOpen(false)} type="button">×</button></header><p className={styles.help}>Reports are confidential. The reported account will not be told who submitted this report.</p><form onSubmit={submit}><label>Reason<select value={reason} onChange={e=>setReason(e.target.value as ReportReason)}>{reasons.map(item=><option key={item} value={item}>{label(item)}</option>)}</select></label><label>Additional details <small>optional</small><textarea maxLength={1000} placeholder="Add context that can help our moderation team…" rows={5} value={details} onChange={e=>setDetails(e.target.value)}/></label><span className={styles.count}>{details.length}/1,000</span>{error&&<p className="form-error">{error}</p>}<footer><button onClick={()=>setOpen(false)} type="button">Cancel</button><button className={styles.submit} disabled={busy} type="submit">{busy?"Submitting…":"Submit report"}</button></footer></form></section></div>}</>;
}
